{
 "title": "Energy Consumption Forecasting",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MAE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "model_mae" }
   ]
  },
  {
   "title": "MAPE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "model_mape" }
   ]
  },
  {
   "title": "Retrains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "retrain_total" }
   ]
  }
 ]
}