apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-system
  name: users-istio-system
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users-istio-system-binding
  namespace: istio-system
subjects:
- kind: Group
  name: users
roleRef:
  kind: Role
  name: users-istio-system
  apiGroup: rbac.authorization.k8s.io