kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users-inference
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["serving.knative.dev"]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["deployments", "services", "pods", "namespaces"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users-inference-binding
subjects:
- kind: Group
  name: users
roleRef:
  kind: Role
  name: users-inference
  apiGroup: rbac.authorization.k8s.io
