
resources:
- mlflow-deployment.yaml
- mlflow-service.yaml
- mlflow-sa.yaml
- mlflow-ingress.yaml

configMapGenerator:
- name: mlflow-configmap
  env: default.env

secretGenerator:
- name: mlflow-secret
  literals:
    # Default password in in-cluster database
    - DB_PASSWORD=KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og
