apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: retraining-job
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retraining-sa
  namespace: retraining-job
secrets:
- name: mysecret
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: retraining-job-deployer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: your-namespace
roleRef:
  kind: ClusterRole
  name: my-cluster-role
  apiGroup: rbac.authorization.k8s.io