apiVersion: v1
kind: PersistentVolume
metadata:
  name: retraining-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: retraining-job
  name: retraining-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: retraining-pv
  resources:
    requests:
      storage: 1Gi

