apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: retraining-job
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retraining-sa
  namespace: retraining-job
secrets:
- name: mysecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: retraining-job-deployer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner-binding-cluster-job-deployer
  labels:
    application-crd-id: kubeflow-pipelines
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: retraining-job-deployer