apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

resources:
- mlflow-namespace.yaml

configMapGenerator:
- name: mlflow-configmap
  env: config.env
  behavior: merge

bases:
- ../postgres
- ../minio
- ../base
